apiVersion: v1
kind: Pod
metadata:
  name: storybook
  labels:
    app: storybook-pod
spec:
  securityContext:
    runAsNonRoot: false
  imagePullPolicy: Always
  containers:
    - name: storybook
      image: 'quay.io/tjelinek/orchestrator-backstage-storybook:latest'
      command: ["/bin/sh","-c"]
      args: ["cd backstage-plugins && git fetch origin pull/{{ .Values.patchId }}/head:from-pr && git checkout from-pr && yarn start:storybook"]
      ports:
        - containerPort: 6006
      securityContext:
        allowPrivilegeEscalation: true
      readinessProbe:
        httpGet:
          path: /
          port: 6006
        initialDelaySeconds: 10
        periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: storybook
spec:
  ports:
    - protocol: TCP
      port: 6006
      targetPort: 6006
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: storybook-pod
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: storybook
spec:
  to:
    kind: Service
    name: storybook
    weight: 100
  port:
    targetPort: 6006
  wildcardPolicy: None
